added 2 new tutorials
icon-community/icon.community pull request #151
Opened 2023-03-14 22:12 UTC by FidelVe

added the following tutorials: 
* How to check if a validator is missing blocks
* How to create a wallet account

2023-03-14 22:34 UTC, han-so1omon requested changes

2023-03-14 22:34 UTC, han-so1omon commented on content/tutorials/2023-03-11-how-to-check-if-a-validator-is-missing-blocks/featured.jpg
Why is "IF" capitalized?

2023-03-14 22:34 UTC, han-so1omon commented on content/tutorials/2023-03-11-how-to-check-if-a-validator-is-missing-blocks/index.md
> +
Please link to the full tutorial in the docs in the top or bottom of this tutorial

2023-03-15 12:46 UTC, FidelVe commented on content/tutorials/2023-03-11-how-to-check-if-a-validator-is-missing-blocks/featured.jpg
fixed

2023-03-21 18:10 UTC, han-so1omon approved these changes

2023-03-21 18:11 UTC, han-so1omon commented
@DavidFBD looks good to me

2023-03-21 18:15 UTC, merged